### PR TITLE
Fix `Find` Method

### LINKED ISSUE #1: Cannot run a Find query
https://github.com/vipul-rawat/gofr-mongo/blob/ae2fd3ba608e7534078bc26b7a836d29544f8328/mongo.go#L41

I have already tried everything to create a Find, but I always get error messages or empty answers.
Have you tested this Find function? if so, can you show an example?

Here is what I tried:

```go
// Error: {"error":{"message":"results argument must be a pointer to a slice, but was a pointer to ptr"}}
func FindAll(ctx *gofr.Context) (interface{}, error) {
	var results []Report

	err := ctx.Mongo.Find(ctx, "reports", bson.M{} /* valid filter */, &results)
	if err != nil {
		fmt.Println("type of: ", reflect.TypeOf(results))
		return nil, err
	}
	fmt.Println("result: ", results)

	return results, nil
}
```

```go
// error: {"data":null}
func FindAll(ctx *gofr.Context) (interface{}, error) {
	var results []Report

	err := ctx.Mongo.Find(ctx, "reports", bson.M{} /* valid filter */, results)
	if err != nil {
		fmt.Println("type of: ", reflect.TypeOf(results))
		return nil, err
	}
	fmt.Println("result: ", results)

	return results, nil
}
```

```go
// error: {"error":{"message":"results argument must be a pointer to a slice, but was a pointer to ptr"}}
func FindAll(ctx *gofr.Context) (interface{}, error) {
	var results Report

	err := ctx.Mongo.Find(ctx, "reports", bson.M{} /* valid filter */, &results)
	if err != nil {
		fmt.Println("type of: ", reflect.TypeOf(results))
		return nil, err
	}
	fmt.Println("result: ", results)

	return results, nil
}
```

```go
// error: {"error":{"message":"results argument must be a pointer to a slice, but was a pointer to ptr"}}
func FindAll(ctx *gofr.Context) (interface{}, error) {
	var results interface{}

	err := ctx.Mongo.Find(ctx, "reports", bson.M{} /* valid filter */, &results)
	if err != nil {
		fmt.Println("type of: ", reflect.TypeOf(results))
		return nil, err
	}
	fmt.Println("result: ", results)

	return results, nil
}
```

```go
// error: {"error":{"message":"results argument must be a pointer to a slice, but was a pointer to ptr"}}
func FindAll(ctx *gofr.Context) (interface{}, error) {
	var results []interface{}

	err := ctx.Mongo.Find(ctx, "reports", bson.M{} /* valid filter */, &results)
	if err != nil {
		fmt.Println("type of: ", reflect.TypeOf(results))
		return nil, err
	}
	fmt.Println("result: ", results)

	return results, nil
}
```

### PR DESCRIPTION
**Pull request by AchimGrolimund**
This should fix the `Find` Method.

This should Fix #1

### CODE REVIEW

**Comment by AchimGrolimund** [comment]
testet with this function:

```go
type ReportData struct {
	DocumentUri        string `bson:"documenturi" json:"documenturi"`
	Referrer           string `bson:"referrer" json:"referrer"`
	ViolatedDirective  string `bson:"violateddirective" json:"violateddirective"`
	EffectiveDirective string `bson:"effectivedirective" json:"effectivedirective"`
	OriginalPolicy     string `bson:"originalpolicy" json:"originalpolicy"`
	Disposition        string `bson:"disposition" json:"disposition"`
	BlockedUri         string `bson:"blockeduri" json:"blockeduri"`
	LineNumber         int    `bson:"linenumber" json:"linenumber"`
	SourceFile         string `bson:"sourcefile" json:"sourcefile"`
	StatusCode         int    `bson:"statuscode" json:"statuscode"`
	ScriptSample       string `bson:"scriptsample" json:"scriptsample"`
}

type Report struct {
	ID     string     `bson:"_id" json:"_id"`
	Report ReportData `bson:"report" json:"report"`
}

func FindAll(ctx *gofr.Context) (interface{}, error) {
	var results []Report

	err := ctx.Mongo.Find(ctx, "reports", bson.M{} /* valid filter */, &results)
	if err != nil {
		return nil, err
	}

	return results, nil
}
```

result:

```
{
	"data": [
		{
			"_id": "660e8b0130b211ddafefff8f",
			"report": {
				"documenturi": "https://wiki****.ch/",
				"referrer": "https://wiki****.ch/en/docker/traefik",
				"violateddirective": "img-src",
				"effectivedirective": "img-src",
				"originalpolicy": "default-src 'none'; connect-src 'self' https://faro-collector-prod-eu-west-3.grafana.net; img-src 'self' https://static.requarks.io/logo/wikijs-butterfly.svg; script-src 'self' 'unsafe-eval'; script-src-elem 'self' 'unsafe-inline' https://unpkg.com; style-src 'self' 'unsafe-inline'; font-src 'self'; manifest-src 'self'; report-uri https://csp.****.ch/report",
				"disposition": "enforce",
				"blockeduri": "data",
				"linenumber": 0,
				"sourcefile": "",
				"statuscode": 200,
				"scriptsample": ""
			}
		},
		{
			"_id": "660eb7f8c4fff2cddcfd0a99",
			"report": {
				"documenturi": "https://hoas.****.ch/service_worker.js",
				"referrer": "",
				"violateddirective": "connect-src",
				"effectivedirective": "connect-src",
				"originalpolicy": "default-src 'none'; connect-src 'self' https://faro-collector-prod-eu-west-3.grafana.net; base-uri 'self'; form-action 'self'; img-src 'self' https://static.requarks.io/logo/wikijs-butterfly.svg; script-src 'self' 'unsafe-eval'; script-src-elem 'self' 'unsafe-inline' https://unpkg.com; style-src 'self' 'unsafe-inline'; font-src 'self'; manifest-src 'self'; report-uri https://csp.****.ch/report",
				"disposition": "enforce",
				"blockeduri": "https://brands.home-assistant.io/_/camera/dark_icon.png",
				"linenumber": 1,
				"sourcefile": "https://hoas.****.ch/service_worker.js",
				"statuscode": 0,
				"scriptsample": ""
			}
		},
	]
}
```

**Comment by AchimGrolimund** [comment]
you can test it with this entry in the `go.mod`:

```
replace github.com/vipul-rawat/gofr-mongo v0.2.0 => github.com/AchimGrolimund/gofr-mongo v0.0.0-20240510184352-afe22ad7efb8
```

**Comment by AchimGrolimund** [comment]
Hello @vipul-rawat  have you already had the opportunity to check my changes to the code?
I would be happy if this would also fit for you, then I can use this integration with `gofr`

**Review by vipul-rawat — APPROVED** [review]

**Comment by vipul-rawat** [comment]
Merged

**Pull request merged**
